
'''
This is the list that acquire.py uses.  Make sure you acquire file imports this as:

from github_list import github_list


'''

github_list = ['iterativv/NostalgiaForInfinity',
 'cl2333/Grokking-the-Coding-Interview-Patterns-for-Coding-Questions',
 'edeng23/binance-trade-bot',
 'donnemartin/system-design-primer',
 'dortania/OpenCore-Legacy-Patcher',
 'eu-digital-green-certificates/dgc-testdata',
 'vinta/awesome-python',
 'freqtrade/freqtrade-strategies',
 'CorentinJ/Real-Time-Voice-Cloning',
 'martinet101/ElevenClock',
 'yt-dlp/yt-dlp',
 'kovidgoyal/calibre',
 'ddbourgin/numpy-ml',
 'Ganapati/RsaCtfTool',
 'public-apis/public-apis',
 'ytdl-org/youtube-dl',
 'ManimCommunity/manim',
 'eternnoir/pyTelegramBotAPI',
 'MrS0m30n3/youtube-dl-gui',
 'Chia-Network/chia-blockchain',
 'microsoft/hummingbird',
 'JulienPalard/Pipe',
 'jorisschellekens/borb',
 'netbox-community/netbox',
 'th3unkn0n/TeleGram-Scraper',
 'twbs/bootstrap',
 'rohan-paul/Awesome-JavaScript-Interviews',
 'cerebral/cerebral',
 'krausest/js-framework-benchmark',
 'pavelk2/social-feed',
 'LeCoupa/awesome-cheatsheets',
 'timcharper/calendar_date_select',
 'NickKaramoff/shareon',
 'fortnightlabs/snowball-js',
 'Artod/baascms',
 'nullobject/tetris',
 'lukasolson/backbone-super',
 'patinencomun/lunar-landing-javascript',
 'sudheerj/awesome-javascript-technologies',
 'nsat/jspredict',
 'tomanagle/JavaScript-design-patterns',
 'electron-userland/electron-forge-templates',
 'baeyun/pregx',
 'Datamart/Komito',
 'yuya-takeyama/Markov-Chain-in-JavaScript',
 'TheAlgorithms/Java',
 'kubernetes-client/java',
 'hmkcode/Java',
 'pubnub/java',
 'bjmashibing/java',
 'json-iterator/java',
 'wesbos/JavaScript30',
 'airbnb/javascript',
 'exercism/java',
 'structurizr/java',
 'trekhleb/javascript-algorithms',
 'joeyajames/Java',
 'winterbe/java8-tutorial',
 'iluwatar/java-design-patterns',
 'lenve/JavaEETest',
 'ReactiveX/RxJava',
 'thaycacac/java',
 'akullpp/awesome-java',
 'Asabeneh/30-Days-Of-JavaScript',
 'google/guava',
 'lydiahallie/javascript-questions',
 'tensorflow/java',
 'shadowsocks/shadowsocks-windows',
 'GavinYellow/SharpSCADA',
 'Unity-Technologies/UnityCsReference',
 'Auburn/FastNoiseLite',
 'egametang/ET',
 'statianzo/Fleck',
 'TheAlgorithms/C-Sharp',
 'Ryujinx/Ryujinx',
 'ArduPilot/MissionPlanner',
 'mono/mono',
 'csinn/CSharp-From-Zero-To-Hero',
 'dynamicexpresso/DynamicExpresso',
 'neuecc/MessagePack-CSharp',
 'JumpAttacker/EnsageSharp',
 'microsoft/FASTER',
 'ServiceStack/ServiceStack.Redis',
 'enyim/EnyimMemcached',
 'QuantConnect/Lean',
 'EasyHttp/EasyHttp',
 'vkhorikov/CSharpFunctionalExtensions',
 'bcgit/bc-csharp',
 'mono/CppSharp',
 'bombomby/optick',
 'rlabrecque/Steamworks.NET',
 'Facepunch/Facepunch.Steamworks',
 'FreeRDP/FreeRDP-Sharp',
 'stratisproject/StratisBitcoinFullNode',
 'whatwg/html',
 'w3c/html',
 'remy/html5demos',
 'mrmrs/html',
 'leemunroe/responsive-html-email-template',
 'html5rocks/www.html5rocks.com',
 'gustavoguanabara/html-css',
 'TelerikAcademy/HTML',
 'coolwanglu/pdf2htmlEX',
 'farhadi/html5sortable',
 'google/material-design-lite',
 'wayou/HTML5_Audio_Visualizer',
 'iandevlin/html5bones',
 'cbracco/html5-test-page',
 'impressivewebs/HTML9-Responsive-Boilerstrap-js',
 'lamberta/html5-animation',
 'modularcode/modular-admin-html',
 'shower/shower',
 'donpark/html2jade',
 'sparksuite/simple-html-invoice-template',
 'mailgun/transactional-email-templates',
 'Masterminds/html5-php',
 'Rits1272/html',
 'paquettg/php-html-parser',
 'codershiyar/html',
 'soundasleep/html2text',
 'charlesmudy/responsive-html-email-template']

 













 


